services:
    mysql:
        image: mysql
        container_name: mysql-container
        ports:
            - "3390:3390"
        networks:
            - colegio-network
        volumes:
            - mysql-volume:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: a1s2d3f4g5h6
        command: --port=3390
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p12345" ]
            interval: 10s
            timeout: 5s
            retries: 5
    # notification
    zookeeper:
        image: confluentinc/cp-zookeeper:7.3.0
        container_name: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        networks:
            - colegio-network
        healthcheck:
            test: [ "CMD-SHELL", "echo 'ruok' | nc -w 2 localhost 2181 || exit 1" ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s
    kafka:
        image: confluentinc/cp-kafka:7.3.0
        networks:
            - colegio-network
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        healthcheck:
            test: [ "CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list" ]
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 30s
    kafdrop:
        image: obsidiandynamics/kafdrop:latest
        networks:
            - colegio-network
        depends_on:
            kafka:
                condition: service_healthy
        ports:
            - "19000:9000"
        environment:
            KAFKA_BROKERCONNECT: kafka:29092
    colegio-auth-ms:
        container_name: colegio-auth-ms
        image: colegio-auth-ms
        build:
            context: ./colegio-auth-ms/
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        networks:
            - colegio-network
        depends_on:
            kafka:
                condition: service_healthy
            mysql:
                condition: service_healthy
        environment:
            JWT_SECRET: VGhpcy1pcy1hLW11Y2gtc3Ryb25nZXItYW5kLXNlY3VyZS1rZXktZm9yLUpoVw==
            DEFAULT_PASSWORD: 10002000
            KAFKA_HOST: kafka:29092
            PORT: 8000
            MYSQL_HOST: mysql:3390
    enrollment-ms-colegio:
        container_name: enrollment-ms-colegio
        image: enrollment-ms-colegio
        build:
            context: ./colegio-enrollment-ms/
            dockerfile: Dockerfile
        ports:
            - "8010:8010"
        networks:
            - colegio-network
        depends_on:
            kafka:
                condition: service_healthy
            mysql:
                condition: service_healthy
        environment:
            KAFKA_HOST: kafka:29092
            PORT: 8010
            MYSQL_HOST: mysql:3390
networks:
    colegio-network:
        driver: bridge

volumes:
    mysql-volume:
        driver: local