CREATE USER IF NOT EXISTS 'root-auth'@'%' IDENTIFIED BY '12345';
CREATE USER IF NOT EXISTS 'root-courses'@'%' IDENTIFIED BY '12345';
CREATE USER IF NOT EXISTS 'root-enrollment'@'%' IDENTIFIED BY '12345';